
GET http://localhost:4004/rest/api/customers()
Authorization: Basic service-user:service-user

###

GET http://localhost:4004/rest/api/products()
Authorization: Basic service-user:service-user

###
GET http://localhost:4004/rest/api/orders()
Authorization: Basic service-user:service-user

###

POST http://localhost:4004/rest/api/createOrder 
Authorization: Basic service-user:service-user
content-type: application/json

{
    "order": 
        {
          "customer": "93cada62-c115-47f9-8a06-b56497a60e11",
          "orderDate": "2024-10-10",
          "orderAmount": 6000.00,
          "currency": "EUR",
          "items": [
            {
              "itemID": 10,  
              "product": "67d85897-dd5a-49b3-bf5c-64df5342b5c2",
              "quantity": 5,
              "itemAmount": 6000.00,
              "currency": "EUR"
            },
            {
              "itemID": 10,  
              "product": "0d785839-a5d9-428e-9a9b-15b4e4895e12",
              "quantity": 3,
              "itemAmount": 6300.00,
              "currency": "EUR"
            }
          ]
        }
}